from GUI.engine.frontend.graphical_elements.graphical_element import Element_2d

import wgpu
import pygfx
import numpy as np

# this class was generated by a LLM

class Scatterplot2DDynamic(Element_2d):
    """
    A 2D scatterplot element with dynamically varying point count.
    
    Key efficiency features:
    - Pre-allocated GPU buffers that grow geometrically (doubling) when needed
    - No re-allocation on every update: reuses existing buffers when possible
    - Efficient partial buffer updates via `update_range` 
    - Uses draw_range to render only the active subset of points
    - Double-buffered CPU arrays to avoid allocation overhead
    
    The buffer capacity starts at `initial_capacity` and grows by a factor of
    `growth_factor` whenever the incoming data exceeds current capacity.
    Points outside the active range are not rendered (via geometry.positions.draw_range).
    
    Parameters
    ----------
    unique_name : str
        Unique identifier for this element.
    parent : Element
        Parent element in the GUI hierarchy.
    bl_xy_rel : tuple
        Bottom-left corner position relative to parent (0-1 range).
    size_xy_rel : tuple
        Size relative to parent (0-1 range).
    initial_capacity : int
        Initial number of points the buffer can hold. Default 10000.
    growth_factor : float
        Factor by which to grow buffers when capacity is exceeded. Default 2.0.
    point_size : int
        Size of points in pixels. Default 2.
    default_colour : tuple
        Default RGBA colour for points. Default (1, 0, 0.1, 1).
    normalize_coords : bool
        If True, normalize input coordinates to fit within element bounds.
        If False, use coordinates as-is (useful for pre-normalized data).
    """
    
    def __init__(self, unique_name, parent, bl_xy_rel, size_xy_rel,
                 initial_capacity=20_000, growth_factor=1.2, 
                 point_size=1, default_colour=(1, 0, 0.1, 1),
                 normalize_coords=False, colour_mode="uniform", point_mode=None, point_mode_params=None):
        super().__init__(unique_name, parent, bl_xy_rel, size_xy_rel, point_mode=point_mode, point_mode_params=point_mode_params)
        
        self.initial_capacity = initial_capacity
        self.growth_factor = growth_factor
        self.point_size = point_size
        self.default_colour = default_colour
        self.normalize_coords = normalize_coords
        self.colour_mode = colour_mode  # "uniform" or "vertex"
        
        # Current number of active points (actual data)
        self._active_count = 0
        # Current buffer capacity
        self._capacity = initial_capacity
        
        # === CPU-side double buffers for positions (avoid allocations) ===
        # These are the working arrays we write into before sending to GPU
        self._positions_cpu = np.zeros((self._capacity, 3), dtype=np.float32)
        self._positions_cpu_swap = np.zeros((self._capacity, 3), dtype=np.float32)
        
        # === CPU-side buffer for colours (only if vertex colour mode) ===
        if self.colour_mode == "vertex":
            self._colours_cpu = np.zeros((self._capacity, 4), dtype=np.float32)
            self._colours_cpu_swap = np.zeros((self._capacity, 4), dtype=np.float32)
        
        # === GPU Buffers ===
        self._create_gpu_resources()
        
    def _create_gpu_resources(self):
        """Create or recreate GPU buffers with current capacity."""
        # Position buffer on GPU
        # Using COPY_DST allows us to update the buffer data
        self._positions_buffer = pygfx.Buffer(
            data=self._positions_cpu,
            usage=wgpu.BufferUsage.COPY_DST | wgpu.BufferUsage.STORAGE,
        )
        
        # Colours buffer (only if using vertex colours)
        if self.colour_mode == "vertex":
            self._colours_buffer = pygfx.Buffer(
                data=self._colours_cpu,
                usage=wgpu.BufferUsage.COPY_DST | wgpu.BufferUsage.STORAGE,
            )
            self._geometry = pygfx.Geometry(
                positions=self._positions_buffer,
                colors=self._colours_buffer
            )
            self._material = pygfx.PointsMaterial(
                size=self.point_size, 
                color_mode="vertex"
            )
        else:
            self._geometry = pygfx.Geometry(positions=self._positions_buffer)
            self._material = pygfx.PointsMaterial(
                size=self.point_size, 
                color=self.default_colour
            )
        
        # Set initial draw range to 0 (nothing to draw yet)
        self._positions_buffer.draw_range = (0, 0)
        
        # Create Points object
        self._points = pygfx.Points(self._geometry, self._material)
        self.register_gfx_object(self._points)
    
    def _grow_buffers(self, required_capacity):
        """
        Grow all buffers to accommodate at least `required_capacity` points.
        Uses geometric growth to amortize reallocation cost.
        """
        new_capacity = self._capacity
        while new_capacity < required_capacity:
            new_capacity = max(int(new_capacity * self.growth_factor), new_capacity + 1)
        
        # Allocate new CPU arrays
        new_positions_cpu = np.zeros((new_capacity, 3), dtype=np.float32)
        new_positions_cpu_swap = np.zeros((new_capacity, 3), dtype=np.float32)
        
        # Copy existing data
        if self._active_count > 0:
            new_positions_cpu[:self._active_count] = self._positions_cpu[:self._active_count]
        
        self._positions_cpu = new_positions_cpu
        self._positions_cpu_swap = new_positions_cpu_swap
        
        if self.colour_mode == "vertex":
            new_colours_cpu = np.zeros((new_capacity, 4), dtype=np.float32)
            new_colours_cpu_swap = np.zeros((new_capacity, 4), dtype=np.float32)
            if self._active_count > 0:
                new_colours_cpu[:self._active_count] = self._colours_cpu[:self._active_count]
            self._colours_cpu = new_colours_cpu
            self._colours_cpu_swap = new_colours_cpu_swap
        
        self._capacity = new_capacity
        
        # Recreate GPU resources with new capacity
        # First, remove old points object from scene
        self.unregister_gfx_object(self._points)
        
        # Create new GPU resources
        self._create_gpu_resources()
        
        # If we had active points, update the GPU with their data
        if self._active_count > 0:
            self._positions_buffer.update_range(0, self._active_count)
            self._positions_buffer.draw_range = (0, self._active_count)
            if self.colour_mode == "vertex":
                self._colours_buffer.update_range(0, self._active_count)
    
    def update_data(self, points_x, points_y, points_colours=None):
        """
        Update the scatterplot with new data.
        
        This is the main method for updating the visualization efficiently.
        It reuses existing buffers when possible and only grows them when needed.
        
        Parameters
        ----------
        points_x : array-like
            X coordinates of points (1D array of length N).
        points_y : array-like
            Y coordinates of points (1D array of length N).
        points_colours : array-like, optional
            Per-point colours as (N, 4) RGBA array or (N, 3) RGB array.
            Only used if colour_mode="vertex". If None and colour_mode="vertex",
            uses a default colour for all points.
            
        Notes
        -----
        - If N > current capacity, buffers will be grown (geometric growth).
        - If N < current capacity, extra buffer space is simply not rendered.
        - Coordinates are normalized to fit within element bounds if normalize_coords=True.
        """
        points_x = np.asarray(points_x, dtype=np.float32).ravel()
        points_y = np.asarray(points_y, dtype=np.float32).ravel()
        
        n_points = len(points_x)
        if len(points_y) != n_points:
            raise ValueError(f"points_x and points_y must have same length, got {n_points} vs {len(points_y)}")
        
        # Check if we need to grow buffers
        if n_points > self._capacity:
            self._grow_buffers(n_points)
        
        # Get element bounds for coordinate transformation
        sz = self.sz
        bl = self.bl
        
        # === Write into swap buffer, then swap (avoids in-place issues) ===
        if self.normalize_coords and n_points > 0:
            # Normalize coordinates to [0, 1] then scale to element bounds
            x_min, x_max = points_x.min(), points_x.max()
            y_min, y_max = points_y.min(), points_y.max()
            
            # Avoid division by zero
            x_range = x_max - x_min
            y_range = y_max - y_min
            if x_range < 1e-8:
                x_range = 1.0
            if y_range < 1e-8:
                y_range = 1.0
            
            # Normalize and scale to element bounds
            self._positions_cpu_swap[:n_points, 0] = ((points_x - x_min) / x_range) * sz[0] + bl[0]
            self._positions_cpu_swap[:n_points, 1] = ((points_y - y_min) / y_range) * sz[1] + bl[1]
        else:
            # Use coordinates as-is (assume pre-normalized or absolute)
            self._positions_cpu_swap[:n_points, 0] = points_x * sz[0] + bl[0]
            self._positions_cpu_swap[:n_points, 1] = points_y * sz[1] + bl[1]
        
        # Z coordinate (depth) from element's bottom-left z
        self._positions_cpu_swap[:n_points, 2] = bl[2]
        
        # Swap buffers
        self._positions_cpu, self._positions_cpu_swap = self._positions_cpu_swap, self._positions_cpu
        
        # Handle colours if in vertex mode
        if self.colour_mode == "vertex":
            if points_colours is not None:
                points_colours = np.asarray(points_colours, dtype=np.float32)
                if points_colours.ndim == 1:
                    # Single colour for all points
                    self._colours_cpu_swap[:n_points] = points_colours
                elif points_colours.shape[0] != n_points:
                    raise ValueError(f"points_colours must have {n_points} rows, got {points_colours.shape[0]}")
                elif points_colours.shape[1] == 3:
                    # RGB -> RGBA (add alpha = 1)
                    self._colours_cpu_swap[:n_points, :3] = points_colours
                    self._colours_cpu_swap[:n_points, 3] = 1.0
                elif points_colours.shape[1] == 4:
                    self._colours_cpu_swap[:n_points] = points_colours
                else:
                    raise ValueError(f"points_colours must have 3 or 4 columns, got {points_colours.shape[1]}")
            else:
                # Default colour
                self._colours_cpu_swap[:n_points] = self.default_colour
            
            # Swap colour buffers
            self._colours_cpu, self._colours_cpu_swap = self._colours_cpu_swap, self._colours_cpu
            
            # Update colour buffer on GPU
            self._colours_buffer.data[:n_points] = self._colours_cpu[:n_points]
            self._colours_buffer.update_range(0, n_points)
        
        # Update GPU buffer with new position data
        # We update the underlying data array and mark the range as dirty
        self._positions_buffer.data[:n_points] = self._positions_cpu[:n_points]
        self._positions_buffer.update_range(0, n_points)
        
        # Update draw range to render only active points
        self._positions_buffer.draw_range = (0, n_points)
        
        # Track active count
        self._active_count = n_points
    
    def clear(self):
        """Clear all points from the scatterplot."""
        self._positions_buffer.draw_range = (0, 0)
        self._active_count = 0
    
    def set_point_size(self, size):
        """Update the point size."""
        self.point_size = size
        self._material.size = size
    
    def set_colour(self, colour):
        """
        Set uniform colour for all points (only works in uniform colour mode).
        
        Parameters
        ----------
        colour : tuple
            RGBA colour tuple.
        """
        if self.colour_mode != "uniform":
            raise ValueError("set_colour only works in uniform colour mode. Use update_data with points_colours for vertex mode.")
        self.default_colour = colour
        self._material.color = colour
    
    @property
    def active_count(self):
        """Number of currently active (visible) points."""
        return self._active_count
    
    @property
    def capacity(self):
        """Current buffer capacity."""
        return self._capacity
    
    def die(self):
        """Clean up GPU resources."""
        if hasattr(self, '_points'):
            self.unregister_gfx_object(self._points)
        super().die()


class Scatterplot2DDynamicMultiSeries(Element_2d):
    """
    A 2D scatterplot that can display multiple data series with different colours.
    
    Each series can be updated independently, and all series share the same
    coordinate space and normalization bounds.
    
    This is useful for comparing multiple datasets on the same plot.
    
    Parameters
    ----------
    unique_name : str
        Unique identifier for this element.
    parent : Element
        Parent element in the GUI hierarchy.
    bl_xy_rel : tuple
        Bottom-left corner position relative to parent (0-1 range).
    size_xy_rel : tuple
        Size relative to parent (0-1 range).
    series_colours : list of tuple
        List of RGBA colours, one per series.
    initial_capacity_per_series : int
        Initial point capacity per series. Default 5000.
    growth_factor : float
        Growth factor when capacity is exceeded. Default 2.0.
    point_size : int
        Point size in pixels. Default 2.
    """
    
    def __init__(self, unique_name, parent, bl_xy_rel, size_xy_rel,
                 series_colours, initial_capacity_per_series=5_000,
                 growth_factor=2.0, point_size=2, point_mode=None, point_mode_params=None):
        super().__init__(unique_name, parent, bl_xy_rel, size_xy_rel, point_mode=point_mode, point_mode_params=point_mode_params)
        
        self.series_colours = series_colours
        self.n_series = len(series_colours)
        self.point_size = point_size
        self.growth_factor = growth_factor
        
        # Create one scatterplot per series
        self._series = []
        for i, colour in enumerate(series_colours):
            # Series are invisible children that share our coordinate space
            series = _InternalScatterSeries(
                capacity=initial_capacity_per_series,
                growth_factor=growth_factor,
                colour=colour,
                point_size=point_size,
                parent_element=self
            )
            self._series.append(series)
    
    def update_series(self, series_index, points_x, points_y, 
                      x_bounds=None, y_bounds=None):
        """
        Update a specific series with new data.
        
        Parameters
        ----------
        series_index : int
            Index of series to update (0 to n_series-1).
        points_x : array-like
            X coordinates.
        points_y : array-like
            Y coordinates.
        x_bounds : tuple, optional
            (x_min, x_max) for normalization. If None, uses data bounds.
        y_bounds : tuple, optional
            (y_min, y_max) for normalization. If None, uses data bounds.
        """
        if series_index < 0 or series_index >= self.n_series:
            raise ValueError(f"series_index must be 0-{self.n_series-1}, got {series_index}")
        
        self._series[series_index].update_data(
            points_x, points_y, x_bounds, y_bounds
        )
    
    def clear_series(self, series_index):
        """Clear a specific series."""
        if series_index < 0 or series_index >= self.n_series:
            raise ValueError(f"series_index must be 0-{self.n_series-1}, got {series_index}")
        self._series[series_index].clear()
    
    def clear_all(self):
        """Clear all series."""
        for series in self._series:
            series.clear()
    
    def die(self):
        """Clean up all series."""
        for series in self._series:
            series.die()
        self._series.clear()
        super().die()


class _InternalScatterSeries:
    """
    Internal helper class for a single series within Scatterplot2DDynamicMultiSeries.
    Not intended for direct use.
    """
    
    def __init__(self, capacity, growth_factor, colour, point_size, parent_element):
        self._capacity = capacity
        self._growth_factor = growth_factor
        self._colour = colour
        self._point_size = point_size
        self._parent = parent_element
        self._active_count = 0
        
        # CPU buffers
        self._positions_cpu = np.zeros((capacity, 3), dtype=np.float32)
        self._positions_cpu_swap = np.zeros((capacity, 3), dtype=np.float32)
        
        # Create GPU resources
        self._create_gpu_resources()
    
    def _create_gpu_resources(self):
        self._positions_buffer = pygfx.Buffer(
            data=self._positions_cpu,
            usage=wgpu.BufferUsage.COPY_DST | wgpu.BufferUsage.STORAGE,
        )
        self._geometry = pygfx.Geometry(positions=self._positions_buffer)
        self._material = pygfx.PointsMaterial(
            size=self._point_size,
            color=self._colour
        )
        self._positions_buffer.draw_range = (0, 0)
        self._points = pygfx.Points(self._geometry, self._material)
        self._parent.register_gfx_object(self._points)
    
    def _grow_buffers(self, required_capacity):
        new_capacity = self._capacity
        while new_capacity < required_capacity:
            new_capacity = int(new_capacity * self._growth_factor)
        
        new_positions_cpu = np.zeros((new_capacity, 3), dtype=np.float32)
        new_positions_cpu_swap = np.zeros((new_capacity, 3), dtype=np.float32)
        
        if self._active_count > 0:
            new_positions_cpu[:self._active_count] = self._positions_cpu[:self._active_count]
        
        self._positions_cpu = new_positions_cpu
        self._positions_cpu_swap = new_positions_cpu_swap
        self._capacity = new_capacity
        
        self._parent.unregister_gfx_object(self._points)
        self._create_gpu_resources()
        
        if self._active_count > 0:
            self._positions_buffer.update_range(0, self._active_count)
            self._positions_buffer.draw_range = (0, self._active_count)
    
    def update_data(self, points_x, points_y, x_bounds=None, y_bounds=None):
        points_x = np.asarray(points_x, dtype=np.float32).ravel()
        points_y = np.asarray(points_y, dtype=np.float32).ravel()
        n_points = len(points_x)
        
        if n_points > self._capacity:
            self._grow_buffers(n_points)
        
        sz = self._parent.sz
        bl = self._parent.bl
        
        if n_points > 0:
            if x_bounds is not None:
                x_min, x_max = x_bounds
            else:
                x_min, x_max = points_x.min(), points_x.max()
            
            if y_bounds is not None:
                y_min, y_max = y_bounds
            else:
                y_min, y_max = points_y.min(), points_y.max()
            
            x_range = max(x_max - x_min, 1e-8)
            y_range = max(y_max - y_min, 1e-8)
            
            self._positions_cpu_swap[:n_points, 0] = ((points_x - x_min) / x_range) * sz[0] + bl[0]
            self._positions_cpu_swap[:n_points, 1] = ((points_y - y_min) / y_range) * sz[1] + bl[1]
            self._positions_cpu_swap[:n_points, 2] = bl[2]
        
        self._positions_cpu, self._positions_cpu_swap = self._positions_cpu_swap, self._positions_cpu
        self._positions_buffer.data[:n_points] = self._positions_cpu[:n_points]
        self._positions_buffer.update_range(0, n_points)
        self._positions_buffer.draw_range = (0, n_points)
        self._active_count = n_points
    
    def clear(self):
        self._positions_buffer.draw_range = (0, 0)
        self._active_count = 0
    
    def die(self):
        self._parent.unregister_gfx_object(self._points)
